Objects: SolidObject BaseObject
	ld -r build/solidobject.o build/baseobject.o -o build/objects.o

SolidObject:
	g++ src/Objects/SolidObject.cc -c -o build/solidobject.o

BaseObject:
	g++ src/Objects/BaseObject.cc -c -o build/baseobject.o
