Renderer: RendererMain RenderElement
	ld -r build/renderer.o build/renderelement.o -o build/renderengine.o

RendererMain:
	g++ src/Renderer/Renderer.cc -c -o build/renderer.o

RenderElement:
	g++ src/Renderer/RenderElement.cc -c -o build/renderelement.o
